/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteFieldArgs } from "./DeleteFieldArgs";
import { FieldCountArgs } from "./FieldCountArgs";
import { FieldFindManyArgs } from "./FieldFindManyArgs";
import { FieldFindUniqueArgs } from "./FieldFindUniqueArgs";
import { Field } from "./Field";
import { FieldService } from "../field.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Field)
export class FieldResolverBase {
  constructor(
    protected readonly service: FieldService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Field",
    action: "read",
    possession: "any",
  })
  async _fieldsMeta(
    @graphql.Args() args: FieldCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Field])
  @nestAccessControl.UseRoles({
    resource: "Field",
    action: "read",
    possession: "any",
  })
  async fields(@graphql.Args() args: FieldFindManyArgs): Promise<Field[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Field, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Field",
    action: "read",
    possession: "own",
  })
  async field(
    @graphql.Args() args: FieldFindUniqueArgs
  ): Promise<Field | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Field)
  @nestAccessControl.UseRoles({
    resource: "Field",
    action: "delete",
    possession: "any",
  })
  async deleteField(
    @graphql.Args() args: DeleteFieldArgs
  ): Promise<Field | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
